//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoko.CSPSolver {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoko.CSPSolver.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=first_unassigned_variable, order_domain_values=lcv , inference=no_inference)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row] for row  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaFuvLcvPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaFuvLcvPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=first_unassigned_variable, order_domain_values=unordered_domain_values, inference=forward_checking )
        ///#s.display(result)
        ///solution =   [[result.get(cell) f [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaFuvUdvFcPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaFuvUdvFcPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=first_unassigned_variable, order_domain_values=unordered_domain_values, inference=mac)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaFuvUdvMacPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaFuvUdvMacPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=first_unassigned_variable, order_domain_values=unordered_domain_values, inference=no_inference)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for ce [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaFuvUdvPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaFuvUdvPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = min_conflicts(s, max_steps=1000000)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row] for row in s.rows]
        ///#print(solution).
        /// </summary>
        internal static string CspAimaMinConflictsPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaMinConflictsPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # reprÃ©sentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne Ã©galement avec des 0 Ã  la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=mrv, order_domain_values=lcv, inference=forward_checking)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row] for row in s.rows]
        ///#pri [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaMrvLcvFcPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaMrvLcvFcPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # reprÃ©sentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne Ã©galement avec des 0 Ã  la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=mrv, order_domain_values=lcv, inference=mac)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row] for row in s.rows]
        ///#print(solution).
        /// </summary>
        internal static string CspAimaMrvLcvMacPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaMrvLcvMacPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=mrv , order_domain_values=lcv, inference=no_inference)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row] for row in s.rows]
        ///#print(sol [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaMrvLcvPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaMrvLcvPipSolver_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # représentation d&apos;un sudoku https://github.com/aimacode/aima-python/blob/master/csp.py#L726
        ///# puzzle = &apos;..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..&apos; fonctionne également avec des 0 à la place des .
        ///import aima3
        ///from aima3.csp import *
        ///s = Sudoku(puzzle)
        ///result = backtracking_search(s, select_unassigned_variable=mrv , order_domain_values=unordered_domain_values, inference=no_inference)
        ///#s.display(result)
        ///solution =   [[result.get(cell) for cell in row] for row in [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CspAimaMrvUdvPipSolver_py {
            get {
                return ResourceManager.GetString("CspAimaMrvUdvPipSolver_py", resourceCulture);
            }
        }
    }
}
